title: Home

views:
  - !include 00_default_view.yaml
  - !include 10_room_view.yaml
  - !include 20_camera_view.yaml
  - !include 30_setting_view.yaml
  - !include 40_device_view.yaml
  - !include 50_info_view.yaml