language: python
python: "3.7.7"
install:
  - pip3 install homeassistant==0.115.6
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all
before_install:
  - mv travis_secrets.yaml secrets.yaml
