language: python
python: "3.8"
install:
  - pip3 install -r requirements.txt
script:
  - hass -c . --script check_config --info all
before_install:
  - touch travis_fake_ssh_key
  - mv travis_secrets.yaml secrets.yaml
