language: python
python: "3.6.4"
install:
  - pip3 install homeassistant==0.92.2
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all
before_install:
  - mv travis_secrets.yaml secrets.yaml
