language: python
python: "3.8.0"
install:
  - pip3 install homeassistant==2021.2.3
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all
before_install:
  - mv travis_secrets.yaml secrets.yaml
