- alias: Project Main to CCTV
  trigger:
    platform: state
    entity_id: input_select.cctv
    to: "Main Entrance"
  action:
    service: script.project_stream_to_kodi
    data_template:
      value: "{{ states('sensor.main_cctv_content_id') }}"

- alias: Project Garage to CCTV
  trigger: 
    platform: state
    entity_id: input_select.cctv
    to: "Garage"
  action:
    service: script.project_stream_to_kodi
    data_template:
      value: "{{ states('sensor.garage_cctv_content_id') }}"

- alias: Stop project to CCTV
  trigger: 
    platform: state
    entity_id: input_select.cctv
    to: "None"
  action:
    service: media_player.media_stop
    data:
      entity_id: media_player.kodi

- alias: Turn off all lights after midnight
  trigger:
    platform: time
    after: "23:59:59"
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: Turn off all lights when no one at home
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: "home"
      to: "not_home"
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: climate.set_operation_mode
      data:
        entity_id: climate.downstairs
        operation_mode: "off"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"
   
- alias: Turn off Nest after 10 minutes
  trigger:
    - platform: state
      entity_id: climate.upstairs
      to: "heat"
      for:
        minutes: 10
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"

- alias: Notify me when off-work traffic is good
  trigger:
    - platform: numeric_state
      entity_id: sensor.work_to_home
      value_template: '{{ state.state }}'
      below: 20
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.henry_phone
        state: work
      - condition: time
        after: '18:00:00'
  action:
    - service: notify.pushbullet
      data_template:
        title: 'Traffic'
        message: 'Back home traffic is down to {{ states.sensor.work_to_home.state }}min'

- alias: Dash Button Milkbaby turns on TV
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_milkbaby
  action:
    - service: switch.toggle
      data:
        entity_id: switch.tv_outlet

- alias: Dash button Quartet turns on bedroom
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_quartet
  action:
    - service: switch.toggle
      data:
        entity_id: switch.bedroom_outlet

- alias: Dash button Dasani turns on study room
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_dasani
  action:
    - service: light.toggle
      data:
        entity_id: light.study_room_lights
