- id: '1602970233608'
  alias: Mi Button Dining Room Single Press
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mibutton_dining
      click_type: single
  condition: []
  action:
  - service: tts.google_translate_say
    entity_id: media_player.google_home
    data:
      message: Lunch is ready
      cache: true
  mode: single
- id: '1603049096680'
  alias: Notify me when motion is detected at main entry
  description: ''
  trigger:
  - platform: device
    domain: binary_sensor
    entity_id: binary_sensor.motion_entry_50b6
    device_id: 9446c182001d11eb99bbd71d6c07a148
    type: motion
  condition: []
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home
      media_content_id: https://raw.githubusercontent.com/CCOSTAN/Home-AssistantConfig/master/config/sounds/one-tone-chime.mp3
      media_content_type: audio/mp4
  mode: single
