- id: '1602970233608'
  alias: Mi Button Dining Room Single Press
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mibutton_dining
      click_type: single
  condition: []
  action:
  - service: media_player.play_media
    entity_id: media_player.google_home
    data:
      entity_id: media_player.google_home
      media_content_id: https://jasonsavard.com/sounds/ding.ogg
      media_content_type: audio/ogg
  mode: single
- id: '1603049096680'
  alias: Notify me when motion is detected at main entry
  description: ''
  trigger:
  - platform: device
    domain: binary_sensor
    entity_id: binary_sensor.motion_entry_50b6
    device_id: 9446c182001d11eb99bbd71d6c07a148
    type: motion
  condition: []
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.google_home
      media_content_id: https://jasonsavard.com/sounds/ios.ogg
      media_content_type: audio/ogg
  mode: single
- id: '1606525914238'
  alias: When motion is detected in basement, turn on lightstripe
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 94470007001d11eb84e5bbc485fc1517
    entity_id: binary_sensor.motion_basement_51d2
    domain: binary_sensor
  condition: []
  action:
  - domain: light
    entity_id: light.yeelight_stripe_0x0000000003426916
    device_id: 26b8e5c530f411ebae68e18886b02859
    type: turn_on
  mode: single
- id: '1614497976602'
  alias: Mi button toggles Xbox switch
  description: ''
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003502655
      click_type: single
  condition: []
  action:
  - type: toggle
    device_id: 5b5134b207345ccbc2473cd4d5f51616
    entity_id: switch.xbox_switch
    domain: switch
  mode: single
