homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 29
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # My customize
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  server_port: !secret server_port
  api_password: !secret http_api_password
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  trusted_networks:
    - 192.168.30.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - sensor.home_to_work
      - sensor.work_to_home
      - sensor.downstairs_thermostat_temperature
      - sensor.upstairs_thermostat_temperature
      - sensor.yr_temperature
      - sensor.downstairs_thermostat_humidity
      - sensor.upstairs_thermostat_humidity
      - sensor.yr_humidity
      - sensor.washer_power
      - binary_sensor.downstairs_away_mode
      - binary_sensor.upstairs_away_mode
    domains:
      - light
      - device_tracker
      - switch

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group

recorder:
  purge_keep_days: 2
  purge_interval: 1
  exclude:
    domains:
      - sun
      - camera
    entities:
      - sensor.since_last_boot
      - sensor.average_load_1m
      - sensor.average_load_5m
      - sensor.average_load_15m
      - sensor.pmu_current
      - sensor.pmu_voltage
      - sensor.pmu_power
      - sensor.ram_free
      - sensor.leave_for_work_time
      - binary_sensor.washer_mode

# Track the sun
sun:

# Weather Prediction
sensor:
  - platform: yr
    monitored_conditions: 
      - temperature
      - humidity
    scan_interval: 600

binary_sensor:
  - platform: template
    sensors:
      upstairs_away_mode:
        entity_id: climate.upstairs
        value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"
  - platform: template
    sensors:
      downstairs_away_mode:
        entity_id: climate.downstairs
        value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"

# Text to speech
tts:
  platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

# Kodi
media_player:
  - platform: kodi
    host: kodi.lan
  - platform: roku
  - platform: mpd
    host: localhost

notify:
  - platform: kodi
    name: kodi
    host: http://kodi.lan
  - platform: pushbullet
    name: pushbullet
    api_key: !secret PUSHBULLET_API_KEY
  - platform: group
    name: yingying_phone
    services:
      - service: pushbullet
        data:
          target: !secret yingying_email

device_tracker:
  - platform: asuswrt
    host: !secret ROUTER_IP
    username: !secret ROUTER_USERNAME
    password: !secret ROUTER_PASSWORD
    interval_seconds: 120
  - platform: owntracks

ffmpeg:
  ffmpeg_bin: /usr/bin/avconv

nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET

logger:
  default: error
  logs:
    homeassistant.components.switch.rpi_rf: debug

# Amazon Echo
emulated_hue:
  expose_by_default: false

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
# username: !secret mqtt_username
# password: !secret mqtt_password
  client_id: home-assistant

light:
  - platform: mqtt
    name: hallway_light
    state_topic: "smartthings/Hallway/switch"
    command_topic: "smartthings/Hallway/switch"
    brightness_state_topic: "smartthings/Hallway/level"
    brightness_command_topic: "smartthings/Hallway/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    payload_on: "on"
    payload_off: "off"
    retain: true
    optimistic: false
    qos: 0
  - platform: yeelight
    devices:
      192.168.30.202:
        name: yeelightstrip
        transition: 1000
        use_music_mode: True
        save_on_change: False

automation: !include_dir_merge_list automation
group: !include group.yaml
zone: !include zone.yaml
script: !include_dir_merge_named script
switch: !include mqtt_switch.yaml
input_boolean: !include input_boolean.yaml

# CCTV
input_select:
  channel:
    name: Channel
    options:
      - ABC News
      - Reuters TV
    initial: ABC News


# New config panel in 0.39
config:
