homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 29
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  customize_glob:
    "binary_sensor.device_*":
       device_class: connectivity

http:
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  ip_ban_enabled: True
  login_attempts_threshold: 3

history:
  include:
    entities:
      - sensor.downstairs_thermostat_temperature
      - sensor.upstairs_thermostat_temperature
      - sensor.downstairs_thermostat_humidity
      - sensor.upstairs_thermostat_humidity
    domains:
      - device_tracker
      - switch
      - light

logbook:
  exclude:
    domains:
      - group

recorder:
  purge_keep_days: 2
  purge_interval: 1
  exclude:
    domains:
      - sun
      - camera
      - weather
    entities:
      - sensor.last_boot
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.memory_free
      - sensor.pmu_power
      - sensor.washer_power
      - sensor.asuswrt_download_speed
      - sensor.asuswrt_upload_speed
      - sensor.asuswrt_download
      - sensor.asuswrt_upload
      - sensor.rt_ac68u_bytes_sent
      - sensor.rt_ac68u_bytes_received
      - sensor.rt_ac68u_packets_sec_sent
      - sensor.rt_ac68u_packets_sec_received
      - sensor.rt_ac68u_kbyte_sec_sent
      - sensor.rt_ac68u_kbyte_sec_received
      - sensor.rt_ac68u_packets_sent
      - sensor.rt_ac68u_packets_received
      - switch.tv_switch
      - switch.nas_outlet

tts:
  platform: google_translate
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret PUSHBULLET_API_KEY

logger:
  default: error

# Amazon Echo
emulated_hue:
  expose_by_default: false
  entities:
    light.yeelightstrip:
      name: "laundry"
      hidden: false
    switch.living_room_outlet:
      name: "living room"
      hidden: false
    switch.bedroom_outlet:
      name: "bedroom"
      hidden: false
    switch.tv_switch:
      name: "tv"
      hidden: false
    input_boolean.night_mode:
      name: "HA Night Routine"
      hidden: false

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  client_id: home-assistant

light:
  - platform: mqtt
    name: hallway_light
    state_topic: "smartthings/Hallway/switch"
    command_topic: "smartthings/Hallway/switch"
    brightness_state_topic: "smartthings/Hallway/level"
    brightness_command_topic: "smartthings/Hallway/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    payload_on: "on"
    payload_off: "off"
    retain: true
    optimistic: false
    qos: 0

automation: !include_dir_merge_list automation
group: !include group.yaml
zone: !include zone.yaml
script: !include_dir_merge_named script
switch: !include_dir_merge_list switches/
input_boolean: !include input_boolean.yaml

# CCTV
input_select:
  channel:
    name: Channel
    options:
      - ABC News
      - Reuters TV
    initial: ABC News

ffmpeg:
config:
frontend:
updater:
discovery:
conversation:
sun:
map:
system_health:
stream:

google_assistant:
  project_id: !secret ASSISTANT_PROJECT_ID
  exposed_domains:
    - switch
    - light
    - group
    - media_player
