homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.device_*":
       device_class: connectivity

http:
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  ip_ban_enabled: True
  login_attempts_threshold: 3

history:
  include:
    entities:
      - sensor.downstairs_thermostat_temperature
      - sensor.upstairs_thermostat_temperature
      - sensor.downstairs_thermostat_humidity
      - sensor.upstairs_thermostat_humidity
    domains:
      - device_tracker
      - switch
      - light

recorder:
  purge_keep_days: 7
  commit_interval: 1
  exclude:
    domains:
      - sun
      - camera
      - weather
    entities:
      - sensor.last_boot
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.memory_free
      - sensor.pmu_power
      - sensor.washer_power
      - sensor.asuswrt_download_speed
      - sensor.asuswrt_upload_speed
      - sensor.asuswrt_download
      - sensor.asuswrt_upload
      - sensor.rt_ac68u_bytes_sent
      - sensor.rt_ac68u_bytes_received
      - sensor.rt_ac68u_packets_sec_sent
      - sensor.rt_ac68u_packets_sec_received
      - sensor.rt_ac68u_kbyte_sec_sent
      - sensor.rt_ac68u_kbyte_sec_received
      - sensor.rt_ac68u_packets_sent
      - sensor.rt_ac68u_packets_received
      - switch.tv_switch

tts:
  platform: google_translate
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

logger:
  default: error

# Amazon Echo
emulated_hue:
  expose_by_default: false
  entities:
    light.yeelight_strip1_286c072f4c87:
      name: "laundry"
      hidden: false
    switch.living_room_outlet:
      name: "living room"
      hidden: false
    switch.bedroom_outlet:
      name: "bedroom"
      hidden: false
    switch.tv_switch:
      name: "tv"
      hidden: false
    input_boolean.night_mode:
      name: "HA Night Routine"
      hidden: false

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant

automation: !include automations.yaml
script: !include_dir_merge_named script
switch: !include_dir_merge_list switches/

default_config:
ffmpeg:
discovery:
stream:

google_assistant:
  project_id: !secret ASSISTANT_PROJECT_ID
  exposed_domains:
    - switch
    - light
    - media_player

influxdb:
  host: influxdb
  database: !secret INFLUXDB_DB
  username: !secret INFLUXDB_USER
  password: !secret INFLUXDB_PASSWD
  tags:
    source: hass
