homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 29
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  server_port: !secret server_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  api_password: !secret http_api_password
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  trusted_networks:
    - 192.168.30.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3

history:
  include:
    entities:
      - sensor.downstairs_thermostat_temperature
      - sensor.upstairs_thermostat_temperature
      - sensor.downstairs_thermostat_humidity
      - sensor.upstairs_thermostat_humidity
    domains:
      - device_tracker
      - switch
      - light

logbook:
  exclude:
    domains:
      - group

recorder:
  purge_keep_days: 2
  purge_interval: 1
  exclude:
    domains:
      - sun
      - camera
    entities:
      - sensor.since_last_boot
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.pmu_current
      - sensor.pmu_voltage
      - sensor.pmu_power
      - sensor.memory_free
      - sensor.washer_power
      - sensor.washer_mode
      - binary_sensor.washer_mode

binary_sensor:
  - platform: template
    sensors:
      upstairs_away_mode:
        entity_id: climate.upstairs
        value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"
  - platform: template
    sensors:
      downstairs_away_mode:
        entity_id: climate.downstairs
        value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"

tts:
  platform: google
  cache: true
  cache_dir: /tmp/tts
  time_memory: 300

notify:
  - platform: pushbullet
    name: pushbullet
    api_key: !secret PUSHBULLET_API_KEY
  - platform: group
    name: yingying_phone
    services:
      - service: pushbullet
        data:
          target: !secret yingying_email

device_tracker:
  - platform: asuswrt
    host: !secret ROUTER_IP
    port: !secret ROUTER_PORT
    username: !secret ROUTER_USERNAME
    ssh_key: !secret ROUTER_SSH_KEY
    interval_seconds: 120
    track_new_devices: False
  - platform: owntracks


nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET

logger:
  default: error
  logs:
    homeassistant.components.switch.rpi_rf: debug

# Amazon Echo
emulated_hue:
  expose_by_default: false

mqtt:
  broker: !secret mqtt_server
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant

light:
  - platform: mqtt
    name: hallway_light
    state_topic: "smartthings/Hallway/switch"
    command_topic: "smartthings/Hallway/switch"
    brightness_state_topic: "smartthings/Hallway/level"
    brightness_command_topic: "smartthings/Hallway/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    payload_on: "on"
    payload_off: "off"
    retain: true
    optimistic: false
    qos: 0

automation: !include_dir_merge_list automation
group: !include group.yaml
zone: !include zone.yaml
script: !include_dir_merge_named script
switch: !include mqtt_switch.yaml
input_boolean: !include input_boolean.yaml

# CCTV
input_select:
  channel:
    name: Channel
    options:
      - ABC News
      - Reuters TV
    initial: ABC News

ffmpeg:
config:
frontend:
updater:
discovery:
conversation:
sun:
map:
