- alias: Turn off all lights when no one at home
  trigger:
    - platform: state
      entity_id: group.family
      from: "home"
      to: "not_home"
      for:
        minutes: 10

  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.all_switches
    - service: climate.set_operation_mode
      data:
        entity_id: climate.downstairs
        operation_mode: "off"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"

