- alias: Dash Button Milkbaby turns on TV
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_milkbaby
  action:
    - service: switch.toggle
      data:
        entity_id: switch.tv_switch

- alias: Dash button Quartet turns on bedroom
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_quartet
    - platform: mqtt
      topic: dashbutton/dash_wilsonjones
  action:
    - service: switch.toggle
      data:
        entity_id: switch.bedroom_outlet

- alias: Dash button Dasani turns on hallway
  trigger:
    - platform: mqtt
      topic: dashbutton/dash_dasani
  action:
    - service: light.toggle
      data:
        entity_id: light.hallway_light
