- alias: Turn off all lights after midnight
  trigger:
    platform: time
    after: "23:59:59"
  action:
    service: light.turn_off
    entity_id: group.all_lights

- alias: Turn off all lights when no one at home
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: "home"
      to: "not_home"
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: climate.set_operation_mode
      data:
        entity_id: climate.downstairs
        operation_mode: "off"
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"
   
- alias: Turn off Nest after 10 minutes
  trigger:
    - platform: state
      entity_id: climate.upstairs
      to: "heat"
      for:
        minutes: 10
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"

