- alias: Turn off all lights after midnight
  trigger:
    platform: time
    at: "23:59:59"
  action:
    - service: light.turn_off
      data:
        entity_id: group.all_lights

- alias: Turn off Nest after 10 minutes
  trigger:
    - platform: state
      entity_id: climate.upstairs
      to: "heat"
      for:
        minutes: 10
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: climate.upstairs
        operation_mode: "off"

