- alias: MI button living room click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000e64642
      click_type: single
  action:
    service: light.toggle
    entity_id: light.gateway_light_04cf8c911730

- alias: MI button living room long press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000e64642
      click_type: long_click_press
  action:
    service: script.log_feeding_time

- alias: MI button bedroom click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003502655
      click_type: single
  action:
    service: switch.toggle
    entity_id: switch.bedroom_outlet

- alias: MI button bedroom long press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003502655
      click_type: long_click_press
  action:
    service: script.log_feeding_time

- alias: MI button dinning room long press
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0003611d02
      click_type: long_click_press
  action:
    service: script.log_feeding_time
