- alias: On Mi button click
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0000e64642
      click_type: single
  action:
    service: light.toggle
    entity_id: light.gateway_light_04cf8c911730
