- alias: Set Upstairs Nest to Eco
  trigger:
    - platform: state
      entity_id: climate.upstairs
      to: "heat"
      for:
        minutes: 10
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.upstairs
        preset_mode: "eco"

- alias: Set Downstairs Nest to Eco
  trigger:
    - platform: state
      entity_id: climate.downstairs
      to: "heat"
      for:
        minutes: 10
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.downstairs
        preset_mode: "eco"

