- alias: Mute speech notification after midnight
  trigger:
    platform: time
    at: "23:59:59"
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.speech_notification

- alias: Resume speech notification in the morning
  trigger:
    platform: time
    at: "09:00:00"
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.speech_notification

- alias: Notify when garage door is open
  trigger:
    platform: state
    entity_id: cover.garage
    from: "closed"
    to: "open"
  action:
    - service: script.tts
      data_template:
        value1: "Garage door is opening"
