- alias: Turn off speaker if idle for 10 min
  trigger:
    - platform: state
      entity_id: media_player.mpd
      to: "idle"
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.speaker_outlet
