- alias: 'Upstairs Light Turn on'
  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_away_mode
      to: 'off'
    - platform: state
      entity_id: group.family
      to: 'home'
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
  
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'

  action:
    service: light.turn_on
    entity_id: group.upstairs

