- alias: Welcome home
  trigger:
    - platform: state
      entity_id: 
        - device_tracker.henry_phone
        - device_tracker.yingying_phone
      from: "not_home"
      to: "home"
      for: "00:02:00"

  action:
    - service: script.tts
      data_template:
        value1: >
          {{ [
          "Welcome back home",
          "Welcome home"
          ] | random }},
          {{ trigger.entity_id.split('.')[1]|replace('_phone', '') }}
