#camera:
#  - platform: ffmpeg
#    input: !secret GARAGE_CCTV_RTSP
#    name: Garage
#  - platform: ffmpeg
#    input: !secret MAIN_CCTV_RTSP
#    name: Main
camera:
  - platform: generic
    still_image_url: https://www.mayline.com/products/images/product/noimage.jpg
    stream_source: !secret GARAGE_CCTV_RTSP
    name: Garage
  - platform: generic
    still_image_url: https://www.mayline.com/products/images/product/noimage.jpg
    stream_source: !secret MAIN_CCTV_RTSP
    name: Main
  - platform: generic
    still_image_url: https://www.mayline.com/products/images/product/noimage.jpg
    stream_source: !secret BABY_WATCH_RTSP
    name: Baby Mon
  - platform: generic
    still_image_url: https://www.mayline.com/products/images/product/noimage.jpg
    stream_source: !secret ENTRYWAY_RTSP
    name: Entry Way

#---------------------------------------
sensor:
  - platform: template
    sensors:
      # A workaround to pass !secret to templating engine
      # https://community.home-assistant.io/t/make-secrets-available-in-templating-engine/10507
      main_cctv_content_id:
        value_template: !secret MAIN_CCTV_RTSP
      garage_cctv_content_id:
        value_template: !secret GARAGE_CCTV_RTSP
#---------------------------------------
input_select:
  cctv:
    name: CCTV
    options:
      - Main Entrance
      - Garage
      - None
    initial: None
#---------------------------------------
automation:
  - alias: Project Main to CCTV
    trigger:
      platform: state
      entity_id: input_select.cctv
      to: "Main Entrance"
    action:
      service: script.project_stream_to_kodi
      data_template:
        value: "{{ states('sensor.main_cctv_content_id') }}"
  
  - alias: Project Garage to CCTV
    trigger: 
      platform: state
      entity_id: input_select.cctv
      to: "Garage"
    action:
      service: script.project_stream_to_kodi
      data_template:
        value: "{{ states('sensor.garage_cctv_content_id') }}"
  
  - alias: Stop project to CCTV
    trigger: 
      platform: state
      entity_id: input_select.cctv
      to: "None"
    action:
      service: media_player.media_stop
      data:
        entity_id: media_player.kodi

