sensor:
  - platform: template
    sensors:
      last_feeding_time:
        value_template: >-
          {{ states.input_datetime.feed_time.state }}

script:
  log_feeding_time:
    sequence:
      - service: input_datetime.set_datetime
        data_template:
          time: "{{ now().strftime('%H:%M:%S') }}"

input_datetime:
  feed_time:
    name: Feed Time
    has_date: false
    has_time: true
