cover:
  - platform: myq
    username: !secret MYQ_USERNAME
    password: !secret MYQ_PASSWORD
    type: liftmaster
#---------------------------------------
sensor:
- platform: template
  sensors:
    garage_status:
      value_template: '{{ states.cover.garage.state }}'
#---------------------------------------
homeassistant:
  customize:
    cover.garage:
      icon: mdi:car
    sensor.garage_status:
      friendly_name: 'State of the door'

alert:
  garage_door_open_long:
    name: Garage Door is still open
    entity_id: sensor.garage_status
    state: 'open'
    repeat: 10
    can_acknowledge: true
    skip_first: true
    notifiers:
      - pushbullet
    
automation:
  - alias: Notify me when garage door is open
    trigger:
      platform: state
      entity_id: cover.garage
      from: "closed"
      to: "open"
    action:
      - service: script.tts
        data_template:
          value1: "Garage door is opening"

