nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET

group:
  thermostats:
    name: Thermostats
    view: no
    entities:
      - climate.downstairs
      - sensor.downstairs_thermostat_humidity
      - climate.upstairs
      - sensor.upstairs_thermostat_humidity

binary_sensor:
  - platform: template
    sensors:
      upstairs_away_mode:
        entity_id: climate.upstairs
        value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"
  - platform: template
    sensors:
      downstairs_away_mode:
        entity_id: climate.downstairs
        value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"

automation:
  - alias: Set Nest to Eco
    trigger:
      - platform: state
        entity_id: climate.upstairs
        to: "heat"
        for:
          minutes: 10
    action:
      - service: climate.set_operation_mode
        data:
          entity_id: climate.upstairs
          operation_mode: "eco"

