nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET

binary_sensor:
  - platform: template
    sensors:
      upstairs_away_mode:
        entity_id: climate.upstairs
        value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"
  - platform: template
    sensors:
      downstairs_away_mode:
        entity_id: climate.downstairs
        value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"
