input_boolean:
  night_mode:
    name: 'Night Mode'

automation:
  - alias: Turn off all lights at night mode
    trigger:
      platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
    action:
      service: script.turn_off_everything
      data:
        entity_id: input_boolean.night_mode
  
  - alias: Turn off night mode in the morning
    trigger:
      platform: sun
      event: sunrise
      offset: '+00:00:00'
    action:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.night_mode
