#---------------------------------------
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /usr
      - type: disk_use_percent
        arg: /usr
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot
  - platform: template
    sensors:
      pmu_power:
        friendly_name_template: "{{ states.switch.nas_outlet.name}} Power"
        value_template: '{{ states.switch.nas_outlet.attributes["current_power_w"] | float | round(2) }}'
        unit_of_measurement: 'W'
