#---------------------------------------
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /usr
      - type: disk_use_percent
        arg: /usr
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot
