homeassistant:
  customize:
    sensor.leave_for_work_time:
      friendly_name: 'Leave for work'
#---------------------------------------
sensor:
  - platform: google_travel_time
    api_key: !secret GOOGLE_API_KEY
    name: Home to Work
    origin: zone.home
    destination: zone.work
    scan_interval: 120
  - platform: google_travel_time
    api_key: !secret GOOGLE_API_KEY
    name: Work to Home
    origin: zone.work
    destination: zone.home
    scan_interval: 120
  - platform: google_travel_time
    api_key: !secret GOOGLE_API_KEY
    name: Henry Location To Home
    origin: device_tracker.henry_phone
    destination: zone.home
    scan_interval: 120
  - platform: template
    sensors:
      leave_for_work_time:
        value_template: '{{ strptime("08:30", "%H:%M") - strptime(states.sensor.home_to_work.state, "%M") }}'
