vacuum:
  - platform: xiaomi_miio
    host: !secret XIAOMI_VACUUM_HOST
    token: !secret XIAOMI_VACUUM_TOKEN

input_boolean:
  vacuum_done:
    name: Vacuum is done

automation:
  - alias: Vacuum is done
    trigger:
      - platform: state
        entity_id: vacuum.xiaomi_vacuum_cleaner
        from: "on"
        to: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacuum_done

sensor:
  - platform: template
    sensors:
      last_vacuum_time:
        value_template: >-
          {{as_timestamp(state_attr('vacuum.xiaomi_vacuum_cleaner', 'clean_stop'))
            | timestamp_custom("%m/%d", true)}}
