switch:
  - platform: edimax
    host: 192.168.30.245
    name: washer

sensor:
  - platform: template
    sensors:
      washer_power:
        value_template: '{{ states.switch.washer.attributes["current_power_w"] | float * 1000000 | round(2) }}'
        unit_of_measurement: 'W'
