sensor:
  - platform: template
    sensors:
      washer_power:
        value_template: '{{ states.switch.washer_outlet.attributes["current_power_w"] | float | round(2) }}'
        unit_of_measurement: 'W'

input_boolean:
  washer_status:
    name: Washer Status
    initial: off

automation:
  - alias: Set washer status to on
    trigger:
      - platform: numeric_state
        entity_id: sensor.washer_power
        above: 10
    condition:
      - condition: state
        entity_id: input_boolean.washer_status
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.washer_status
  - alias: Set washer status to off
    trigger:
      - platform: numeric_state
        entity_id: sensor.washer_power
        below: 3
        for:
          minutes: 1
    condition:
      - condition: state
        entity_id: input_boolean.washer_status
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.washer_status
