group:
  washer_card:
    name: Laundary
    entities:
      - input_boolean.laundry_done
      - switch.washer_outlet
      - binary_sensor.washer_mode
      - sensor.washer_power

sensor:
  - platform: template
    sensors:
      washer_power:
        value_template: '{{ states.switch.washer_outlet.attributes["current_power_w"] | float | round(2) }}'
        unit_of_measurement: 'W'

binary_sensor:
  - platform: template
    sensors:
      washer_mode:
        value_template: '{{ states.sensor.washer_power.state | int > 10 }}'

input_boolean:
  laundry_done:
    name: Laundry notification

automation:
  - alias: Laundary is done
    trigger:
      - platform: state
        entity_id: binary_sensor.washer_mode
        to: "off"
        for: "00:03:00"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.laundry_done
